std = "lua51"

unused_args = false
trailing_whitespace = false
max_line_length = false

ignore = {
    "211", -- unused variable
    "213", -- unused loop variable
    "421", -- shadowing in inner scope
    "422", -- shadowing argument
    "411", -- redefined variable
    "612", -- trailing whitespace
    "614", -- trailing whitespace in comment
}

exclude_files = {
    "libs/**",
    "protobuf/**",
}

globals = {
    "MyslotExports",
    "MyslotSettings",
    "SLASH_MYSLOT1",
    "SlashCmdList",
    "StaticPopupDialogs",
    "opt",
}

read_globals = {
    "ACCEPT",
    "ACTIONBARS_LABEL",
    "BOOKTYPE_PROFESSION",
    "BOOKTYPE_SPELL",
    "BOTTOMLEFT_ACTIONBAR_PAGE",
    "BOTTOMRIGHT_ACTIONBAR_PAGE",
    "BackdropTemplateMixin",
    "bit",
    "CANCEL",
    "CHARACTER_SPECIFIC_MACROS",
    "CLASS",
    "CLOSE",
    "C_AddOns",
    "C_EquipmentSet",
    "C_Item",
    "C_KeyBindings",
    "C_MountJournal",
    "C_PetJournal",
    "C_SpecializationInfo",
    "C_Spell",
    "C_SpellBook",
    "C_UI",
    "ClearCursor",
    "CreateFrame",
    "CreateMacro",
    "DEFAULT_CHAT_FRAME",
    "DELETE",
    "DeleteMacro",
    "Enum",
    "FindBaseSpellByID",
    "GENERAL_MACROS",
    "GameTooltipText",
    "GetActionInfo",
    "GetBinding",
    "GetBuildInfo",
    "GetCurrentBindingSet",
    "GetCursorInfo",
    "GetFlyoutInfo",
    "GetFlyoutSlotInfo",
    "GetLocale",
    "GetMacroInfo",
    "GetNumBindings",
    "GetNumMacros",
    "GetNumSpecGroups",
    "GetNumSpellTabs",
    "GetPetActionInfo",
    "GetProfessionInfo",
    "GetProfessions",
    "GetPvpTalentInfoByID",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpellBookItemInfo",
    "GetSpellTabInfo",
    "GetTalentInfo",
    "GetTalentTabInfo",
    "InCombatLockdown",
    "IsPetActive",
    "IsWindowsClient",
    "LEFT_ACTIONBAR_PAGE",
    "LEVEL",
    "LibStub",
    "MACRO",
    "MAX_ACCOUNT_MACROS",
    "MAX_CHARACTER_MACROS",
    "MAX_TALENT_TIERS",
    "MULTIBAR_5_ACTIONBAR_PAGE",
    "MULTIBAR_6_ACTIONBAR_PAGE",
    "MULTIBAR_7_ACTIONBAR_PAGE",
    "MenuResponse",
    "MenuUtil",
    "NEW",
    "NONE_CAPS",
    "NUM_PET_ACTION_SLOTS",
    "NUM_TALENT_COLUMNS",
    "OPTIONS",
    "OPTION_SHOW_ACTION_BAR",
    "OTHER",
    "PET",
    "PLAYER",
    "PickupAction",
    "PickupMacro",
    "PickupPetAction",
    "PickupPetSpell",
    "PlaceAction",
    "PlayerSpellsFrame",
    "PlayerSpellsFrame_LoadUI",
    "RED_FONT_COLOR",
    "RIGHT_ACTIONBAR_PAGE",
    "SAVE",
    "SPECIALIZATION",
    "SPELLBOOK_PAGENUMBERS",
    "SPELLS_PER_PAGE",
    "SaveBindings",
    "SetBinding",
    "Settings",
    "StaticPopup_Hide",
    "StaticPopup_Show",
    "TALENTS",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_GetSelectedValue",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_RefreshAll",
    "UIDropDownMenu_SetSelectedValue",
    "UIDropDownMenu_SetText",
    "UIDropDownMenu_SetWidth",
    "UIParent",
    "UnitClass",
    "UnitLevel",
    "UnitName",
    "YELLOW_FONT_COLOR",
    "date",
    "gsub",
    "strsub",
    "strtrim",
    "strupper",
    "tAppendAll",
}

files = {
    ["locales.lua"] = {
        ignore = { "542" }, -- empty localization stubs
    },
}
