-- DO NOT EDIT THIS FILE, GENERATED BY LUAPB-SAVEAST
local _, ADDONSELF = ...

local t = {
-- Table: {1}
{
   ["types"]={2},
},
-- Table: {2}
{
   {3},
   {4},
   {5},
   {6},
   {7},
   {38},
   ["Bind"]={6},
   ["Slot"]={4},
   ["Macro"]={5},
   ["Charactor"]={3},
   ["Key"]={7},
   ["ClickBinding"]={38},
},
-- Table: {3}
{
   ["fields"]={8},
   ["name"]="Charactor",
   [".type"]="message",
},
-- Table: {4}
{
   ["fields"]={9},
   ["name"]="Slot",
   [".type"]="message",
   ["types"]={10},
},
-- Table: {5}
{
   ["fields"]={11},
   ["name"]="Macro",
   [".type"]="message",
},
-- Table: {6}
{
   ["fields"]={12},
   ["name"]="Bind",
   [".type"]="message",
},
-- Table: {7}
{
   ["fields"]={13},
   ["name"]="Key",
   [".type"]="message",
},
-- Table: {8}
{
   {14},
   {15},
   {16},
   {17},
   {18},
   {40},
   {19},
   {20},
   ["ver"]={19},
   ["bind"]={15},
   ["slot"]={14},
   ["macro"]={16},
   ["petslot"]={17},
   ["name"]={20},
   ["cooldownManager"]={18},
   ["clickBinding"]={40},
},
-- Table: {9}
{
   {21},
   {22},
   {23},
   {24},
   ["id"]={21},
   ["type"]={22},
   ["index"]={23},
   ["strindex"]={24},
},
-- Table: {10}
{
   {25},
   ["SlotType"]={25},
},
-- Table: {11}
{
   {26},
   {27},
   {28},
   {29},
   ["id"]={28},
   ["icon"]={29},
   ["name"]={26},
   ["body"]={27},
},
-- Table: {12}
{
   {30},
   {31},
   {32},
   {33},
   ["command"]={33},
   ["key1"]={31},
   ["id"]={30},
   ["key2"]={32},
},
-- Table: {13}
{
   {34},
   {35},
   {36},
   ["mod"]={35},
   ["key"]={34},
   ["keycode"]={36},
},
-- Table: {14}
{
   ["ftype"]="Slot",
   ["name"]="slot",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=1,
},
-- Table: {15}
{
   ["ftype"]="Bind",
   ["name"]="bind",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=2,
},
-- Table: {16}
{
   ["ftype"]="Macro",
   ["name"]="macro",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=3,
},
-- Table: {17}
{
   ["ftype"]="Slot",
   ["name"]="petslot",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=4,
},
-- Table: {18}
{
   ["ftype"]="string",
   ["name"]="cooldownManager",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=5,
},
-- Table: {19}
{
   ["ftype"]="uint32",
   ["name"]="ver",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=14,
},
-- Table: {20}
{
   ["ftype"]="string",
   ["name"]="name",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=15,
},
-- Table: {21}
{
   ["ftype"]="uint32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {22}
{
   ["ftype"]="SlotType",
   ["name"]="type",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {23}
{
   ["ftype"]="uint32",
   ["name"]="index",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=3,
},
-- Table: {24}
{
   ["ftype"]="string",
   ["name"]="strindex",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=4,
},
-- Table: {25}
{
   [".type"]="enum",
   ["name"]="SlotType",
   ["values"]={37},
},
-- Table: {26}
{
   ["ftype"]="string",
   ["name"]="name",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {27}
{
   ["ftype"]="string",
   ["name"]="body",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {28}
{
   ["ftype"]="uint32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=3,
},
-- Table: {29}
{
   ["ftype"]="string",
   ["name"]="icon",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=4,
},
-- Table: {30}
{
   ["ftype"]="uint32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {31}
{
   ["ftype"]="Key",
   ["name"]="key1",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=2,
},
-- Table: {32}
{
   ["ftype"]="Key",
   ["name"]="key2",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=3,
},
-- Table: {33}
{
   ["ftype"]="string",
   ["name"]="command",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=15,
},
-- Table: {34}
{
   ["ftype"]="uint32",
   ["name"]="key",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {35}
{
   ["ftype"]="uint32",
   ["name"]="mod",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {36}
{
   ["ftype"]="string",
   ["name"]="keycode",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=15,
},
-- Table: {37}
{
   "SPELL",
   "ITEM",
   "MACRO",
   "FLYOUT",
   "EMPTY",
   "EQUIPMENTSET",
   "SUMMONPET",
   "COMPANION",
   "SUMMONMOUNT",
   "OUTFIT",
   ["EMPTY"]=5,
   ["FLYOUT"]=4,
   ["SPELL"]=1,
   ["OUTFIT"]=10,
   ["ITEM"]=2,
   ["SUMMONMOUNT"]=9,
   ["SUMMONPET"]=7,
   ["MACRO"]=3,
   ["COMPANION"]=8,
   ["EQUIPMENTSET"]=6,
},
-- Table: {38}
{
   ["fields"]={39},
   ["name"]="ClickBinding",
   [".type"]="message",
},
-- Table: {39}
{
   {41},
   {42},
   {43},
   {44},
   ["type"]={41},
   ["actionID"]={42},
   ["button"]={43},
   ["modifiers"]={44},
},
-- Table: {40}
{
   ["ftype"]="ClickBinding",
   ["name"]="clickBinding",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=6,
},
-- Table: {41}
{
   ["ftype"]="uint32",
   ["name"]="type",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {42}
{
   ["ftype"]="uint32",
   ["name"]="actionID",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {43}
{
   ["ftype"]="string",
   ["name"]="button",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=3,
},
-- Table: {44}
{
   ["ftype"]="uint32",
   ["name"]="modifiers",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=4,
},
}
   local function loadast()
      local tables = t
      for idx = 1,#tables do
         local tolinki = {}
         for i,v in pairs( tables[idx] ) do
            if type( v ) == "table" then
               tables[idx][i] = tables[v[1]]
            end
            if type( i ) == "table" and tables[i[1]] then
               table.insert( tolinki,{ i,tables[i[1]] } )
            end
         end
         -- link indices
         for _,v in ipairs( tolinki ) do
            tables[idx][v[2]],tables[idx][v[1]] =  tables[idx][v[1]],nil
         end
      end
      return tables[1]
   end

ADDONSELF.ast = loadast()